name:  Print Hello World

on:  
  push:

jobs:
  print:
    runs-on:  ubuntu-latest
    steps:
      - name:  Print Hello
        run: echo "Hello World"
      - name: Run file
        run: node index.js